# Generated by Django 2.0.1 on 2018-02-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featured',
            options={'ordering': ['name'], 'verbose_name': 'Featured product', 'verbose_name_plural': 'Featured products'},
        ),
    ]
