# Generated by Django 2.0.1 on 2018-02-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180208_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='short_description',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
