# Generated by Django 2.0.1 on 2018-02-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180208_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True),
        ),
    ]
