# Generated by Django 2.0.1 on 2018-02-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180208_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured',
            name='category',
        ),
        migrations.RemoveField(
            model_name='featured',
            name='manufactured_by',
        ),
        migrations.RemoveField(
            model_name='featured',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='featured',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='featured',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='featured',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='add_to_featured_products',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Featured',
        ),
    ]
