# Generated by Django 2.0.1 on 2018-02-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20180215_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='brand_image',
            field=models.ImageField(default=None, upload_to='manufacturers/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='brand_image',
            field=models.ImageField(default=None, upload_to='vendors/'),
        ),
    ]
