# Generated by Django 2.0.1 on 2018-02-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20180215_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='brand_image',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='brand_image',
        ),
    ]
