# Generated by Django 2.0.1 on 2018-02-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20180215_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='brand_image',
            field=models.ImageField(upload_to='manufacturers/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='brand_image',
            field=models.ImageField(upload_to='vendors/'),
        ),
    ]
