# Generated by Django 2.0.1 on 2018-02-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20180215_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='brand_image',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='brand_image',
        ),
    ]
