# Generated by Django 2.0.1 on 2018-02-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20180215_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='name',
            new_name='size',
        ),
    ]
