# Generated by Django 2.0.1 on 2018-02-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20180215_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_shop', models.CharField(max_length=30)),
                ('type_of_shop', models.CharField(max_length=30)),
                ('location_of_shop', models.CharField(max_length=30)),
                ('city', models.CharField(choices=[('kathmandu', 'Kathmandu'), ('bhaktapur', 'Bhaktapur'), ('lalitpur', 'Lalitpur')], default='kathmandu', max_length=10)),
                ('contact_no', models.CharField(max_length=10)),
                ('first_name_of_owner', models.CharField(max_length=30)),
                ('last_name_of_owner', models.CharField(max_length=30)),
                ('contact_no_of_owner', models.CharField(max_length=10)),
                ('percent_of_share_willing_to_give', models.CharField(max_length=3)),
                ('delivery_by_self', models.BooleanField()),
                ('can_make_brand_image_for_shop', models.BooleanField()),
                ('question', models.TextField(blank=True)),
                ('accepts_tac', models.BooleanField()),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
    ]
