# Generated by Django 2.0.1 on 2018-02-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='delivery_by_self',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5),
        ),
    ]
