# Generated by Django 2.0.1 on 2018-02-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20180217_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='accepts_tac',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='can_make_brand_image_for_shop',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='application',
            name='delivery_by_self',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
