# Generated by Django 2.0.1 on 2018-02-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20180217_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='can_make_brand_image_for_shop',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
    ]
