# Generated by Django 2.0.1 on 2018-03-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20180312_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
