# Generated by Django 2.0.1 on 2018-03-17 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0029_product_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAddedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
                ('subcategory', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=300)),
                ('manufactured_by', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_colors', models.CharField(max_length=50)),
                ('available_sizes', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='vendor_added_products/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, upload_to='vendor_added_products/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, upload_to='vendor_added_products/%Y/%m/%d')),
                ('image4', models.ImageField(blank=True, upload_to='vendor_added_products/%Y/%m/%d')),
                ('image5', models.ImageField(blank=True, upload_to='vendor_added_products/%Y/%m/%d')),
                ('stock', models.PositiveIntegerField()),
                ('for_sale', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('short_description', models.CharField(blank=True, max_length=350)),
                ('description', models.TextField()),
                ('features', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('added_to_products', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
