# Generated by Django 2.0.1 on 2018-03-21 06:57

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20180321_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousal',
            name='image1',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, size=[360, 1170], upload_to=''),
        ),
    ]
