# Generated by Django 2.0.1 on 2018-03-21 07:26

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20180321_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousal',
            name='image1',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, size=[1170, 360], upload_to=''),
        ),
    ]
