# Generated by Django 2.0.1 on 2018-02-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_ordereditem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='nearest_place',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
