# Generated by Django 2.0.1 on 2018-02-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180209_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonenumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('frequency', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['frequency'],
                'verbose_name_plural': 'Customer phonenumbers',
                'verbose_name': 'Customer phonenumber',
            },
        ),
    ]
