# Generated by Django 2.0.1 on 2018-02-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20180210_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-frequency'], 'verbose_name': 'Customer phonenumber', 'verbose_name_plural': 'Customer phonenumbers'},
        ),
    ]
