# Generated by Django 2.0.1 on 2018-02-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180213_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
